Rails.application.routes.draw do
  # generated by scaffold
  # resources :contacts

  # taken from railscast 396
  resources :contacts do
    collection { post :import }
  end

  # You can have the root of your site routed with "root"
  root 'contacts#index'

end
